//noinspection SpellCheckingInspection
pub const VENDOR_KEYWORDS_MAP: &[(&str, &str)] = &[
    ("temurin", "Eclipse Temurin"),
    ("adoptium", "Eclipse Temurin"),
    ("adoptopenjdk", "AdoptOpenJDK"),
    ("corretto", "Amazon Corretto"),
    ("amazon", "Amazon Corretto"),
    ("zulu", "Azul Zulu"),
    ("azul", "Azul Systems"),
    ("liberica", "BellSoft Liberica"),
    ("bellsoft", "BellSoft Liberica"),
    ("microsoft", "Microsoft OpenJDK"),
    ("sapmachine", "SAP SapMachine"),
    ("red hat", "Red Hat OpenJDK"),
    ("redhat", "Red Hat OpenJDK"),
    ("dragonwell", "Alibaba Dragonwell"),
    ("alibaba", "Alibaba Dragonwell"),
    ("bisheng", "Huawei BiSheng"),
    ("huawei", "Huawei BiSheng"),
    ("kona", "Tencent Kona"),
    ("tencent", "Tencent Kona"),
    ("graalvm", "GraalVM"),
    ("mandrel", "Mandrel (GraalVM)"),
    ("semeru", "IBM Semeru"),
    ("openj9", "IBM OpenJ9"),
    ("j9", "IBM OpenJ9"),
    ("zing", "Azul Prime (Zing)"),
    ("prime", "Azul Prime"),
    ("jbr", "JetBrains Runtime"),
    ("jetbrains", "JetBrains Runtime"),
    ("trava", "Trava OpenJDK"),
    ("ojdkbuild", "OJDKBuild"),
    ("debian", "Debian OpenJDK"),
    ("ubuntu", "Ubuntu OpenJDK"),
    ("alpine", "Alpine Linux OpenJDK"),
    ("openjdk", "OpenJDK"),
    ("oracle", "Oracle Java"),
    ("java(tm)", "Oracle Java"),
];
